### ISSUE TITLE
[Bug]: new weapon sprites are all off-center

### ISSUE THREAD

**Issue by messagecypher** [Darkrp-community/OpenKeep#149]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

RogueTown

### Describe the issue

all the new weapon sprites are off center

**Comment by messagecypher** [comment]
off center in the inventory and off center on your character

**Comment by NPC1314** [comment]
Still some issues, shovel works good, others like scimitar and wooden staff less so. Needs more digging

**Comment by BadAtThisGame302** [comment]
I believe this was fixed awhile ago.

**Comment by ThePainkiller** [comment]
No it's not fixed. Longbow is still off center, as most 64x32 weapons are.

**Comment by NPC1314** [comment]
Basically the issue is changing to big sprites.
Using the bigboy var can sort the inventory offset
The inhand offset needs manual adjustments of the offsets
The backslot offset cant be fixed without making something similar to bigboy var screen loc adjustments.
